sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        W9a35eFtl3yZ1twQ0c0jmwZaIy5lQ8oJN4fZUpCmKrzI8g0i+CC6LadYjrj/CtXeIwL1JMUOJhAMqBLy8FvYDcfYf8RVa72R/L4zIofYNi9P0NB+4tJoLfYaOvwnJIxh78WeWXSx+/DaZmVi3zdXt+yRM5DdiAR4Y8XTRnY7y5gq9bQgo3wb6Z3oVw++bBMR3X4jvTYt4XTDpyVnl8BqUf3mCQIX8uPEL5MDOMLCySBsvcL9wEIFiORnbZ9neEVaDu8cetBB6ySTaHJ9ylZDpHlnz/EV4VW+mEgwAm5FCazJaPr+4tBVnbdzLI9TbjaIRnjUrsyngHxvK42zP4jqH4MUePbNAZaqvivSDIM2TkK2QE9H2YHFtwz2wTmslGupl/eq+9Px4zSW2gODDYACDyRtZ8LtUGoTxwoggM2BoQIeDRlmsbR5sNPJWq6zrOCMTXgRJw1CVtSQPGS9buR2PLoun0rsyduRSX3Mn9gczeNa6e1JwQrMom7scxyYlfZNQyL2N8IOVFtQeO6aJCCqm/Tj2ygrNVc+eMbN9qHygpRohJU+n1mR3tpVY5rGqrhA0FVpbyzdbNAFFYNlMkU9ff7EzYYYdik1/DTxmyQst2jY3I5+hSUYxkETDnyWnOO6JhIG5akbyQUO7Mnobcd1I15jWWILOe/2xuqqJ7ZFan4=
    - secure: >-
        KHqhe9jQU8zL4opKjLiNh9f3qDCOd001rjhj3cPQaCGROPLERy9NIIgu8shgecG6db9+/Cgin6ed5AefgRMykyvMQa7lFvYC7oDlQY4M8E99FKo1TVnVfItmHuqRkB58gvG4UgL8kAK0rEw5/yIsUS4gQs6l1juCgRzQ4kqQg0XT3chewRlrJoIm5RZ0JSOPeP7tBjH6CtVraojCT4gPi9BBYkE/IaIS6iY4i+MlafciI0Wy/szdsY86zbUquEIEphbKkttdEtwV8VyJtAEzR2eL+4vOfPSjgkzyZmP3rIR5rWGEZuYuoYaEEks6Mx32MK1xnVcXcSBj5vsHFyy26V0kfqELMJmXNxBDbHeJjOwYqxWruDkv+QbmaM3L5ZlP71/DRY9DNdKayKD4y2EJhMc61wresxPCZPoRYOMmuCN4Drm4bYrYp2WgSoPK9R6ffose4qtjv3IzwJfhqHs4+9/B9uBTCDlVdXWmAKLkutWlxV9vxwfvNgIy1VrC9V2cRcKU3PPkuLZ0h0cm4R9MGA/jJINYldWufb7HmnOEDgMjqPhPfIvDKSTJM9iuAa8dXEAqinjSr3QNnfFInniWV+hsBlU2wQSbFPKcNvpsuNhXsKOlk2ZRj/bUkurh0Jc/KNzBc3g+3g6DbyoAHIhf5xf6RrHDiGIVSWI10UJIhS8=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
